name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    # matrix: run the same job for different configurations (e.g. runners, node versions)
    strategy:
      matrix:
        node-version: [14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    # use matric context object to access defined matrix values
    # job will then run multiple times in parallel: once per matrix value
    # AND for ALL matrix value combinations, if you have multiple
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
