name: Reusable Deploy
# make workflow callable for other workflows
on:
  workflow_call:
    # add all inputs this workflow needs to execute somewhere else
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        # if required to succeed workflow
        required: false
        # if 'required: false' -> you can set default value for 'artifact-name' key
        default: dist
        type: string # or number, boolean
      # ... other keys as you like

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          # use inputs context object
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading ..."
