name: Reusable Deploy
# make workflow callable for other workflows
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying and uploading ..."
