name: Using Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    needs: build
    # to re-use workflow, point to path of re-usable workflow
    # here: relative path inside current repo
    # also possible: absolute path to another rep
    uses: ./.github/workflows/09_reusable-workflow.yml
